services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER:-ProstateHue26}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-ProstateHue2026}
      POSTGRES_DB: ProstateHue
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file: ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file: ./frontend/.env.local
    depends_on:
      - backend

  db-admin:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
