services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER:-ProstateHue26}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-ProstateHue2026}
      POSTGRES_DB: ProstateHue
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file: ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://103.149.87.0:8000}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://103.149.87.0:8000}
    depends_on:
      - backend

  db-admin:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
